//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservBigBird
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NewDevbigbirdEntities : DbContext
    {
        public NewDevbigbirdEntities()
            : base("name=NewDevbigbirdEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<LoginNewTbl> LoginNewTbls { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Role_Account> Role_Account { get; set; }
    }
}
